from utils import *
####################

def help_rc_text(self):
    print 'help_rc_text: remotecontrol kodi'
    print 'usage: rc_text "My Text"'

def do_rc_text(self, args):
    #(args, _options) = parse_arguments(args)
    res = self.ph.RC_text(args)
    print res



####################

def help_rc(self):
    print 'help_rc: remotecontrol kodi'
    print 'usage: rc pageup'

def do_rc(self, args):
    (args, _options) = parse_arguments(args)
    res = self.ph.RC(args[0])
    print res

def complete_rc(self, text, line, beg, end):
    parts = line.split(' ')
    if len(parts) == 2:
        return tab_completer([
                              "left",
                              "right",
                              "up",
                              "down",
                              "pageup",
                              "pagedown",
                              "select",
                              "highlight",
                              "parentdir",
                              "parentfolder",
                              "back",
                              "previousmenu",
                              "info",
                              "pause",
                              "stop",
                              "skipnext",
                              "skipprevious",
                              "fullscreen",
                              "aspectratio",
                              "stepforward",
                              "stepback",
                              "bigstepforward",
                              "bigstepback",
                              "osd",
                              "showsubtitles",
                              "nextsubtitle",
                              "codecinfo",
                              "nextpicture",
                              "previouspicture",
                              "zoomout",
                              "zoomin",
                              "playlist",
                              "queue",
                              "zoomnormal",
                              "zoomlevel1",
                              "zoomlevel2",
                              "zoomlevel3",
                              "zoomlevel4",
                              "zoomlevel5",
                              "zoomlevel6",
                              "zoomlevel7",
                              "zoomlevel8",
                              "zoomlevel9",
                              "nextcalibration",
                              "resetcalibration",
                              "analogmove",
                              "rotate",
                              "rotateccw",
                              "close",
                              "subtitledelayminus",
                              "subtitledelay",
                              "subtitledelayplus",
                              "audiodelayminus",
                              "audiodelay",
                              "audiodelayplus",
                              "subtitleshiftup",
                              "subtitleshiftdown",
                              "subtitlealign",
                              "audionextlanguage",
                              "verticalshiftup",
                              "verticalshiftdown",
                              "nextresolution",
                              "audiotoggledigital",
                              "number0",
                              "number1",
                              "number2",
                              "number3",
                              "number4",
                              "number5",
                              "number6",
                              "number7",
                              "number8",
                              "number9",
                              "osdleft",
                              "osdright",
                              "osdup",
                              "osddown",
                              "osdselect",
                              "osdvalueplus",
                              "osdvalueminus",
                              "smallstepback",
                              "fastforward",
                              "rewind",
                              "play",
                              "playpause",
                              "delete",
                              "copy",
                              "move",
                              "mplayerosd",
                              "hidesubmenu",
                              "screenshot",
                              "rename",
                              "togglewatched",
                              "scanitem",
                              "reloadkeymaps",
                              "volumeup",
                              "volumedown",
                              "mute",
                              "backspace",
                              "scrollup",
                              "scrolldown",
                              "analogfastforward",
                              "analogrewind",
                              "moveitemup",
                              "moveitemdown",
                              "contextmenu",
                              "shift",
                              "symbols",
                              "cursorleft",
                              "cursorright",
                              "showtime",
                              "analogseekforward",
                              "analogseekback",
                              "showpreset",
                              "presetlist",
                              "nextpreset",
                              "previouspreset",
                              "lockpreset",
                              "randompreset",
                              "increasevisrating",
                              "decreasevisrating",
                              "showvideomenu",
                              "enter",
                              "increaserating",
                              "decreaserating",
                              "togglefullscreen",
                              "nextscene",
                              "previousscene",
                              "nextletter",
                              "prevletter",
                              "jumpsms2",
                              "jumpsms3",
                              "jumpsms4",
                              "jumpsms5",
                              "jumpsms6",
                              "jumpsms7",
                              "jumpsms8",
                              "jumpsms9",
                              "filter",
                              "filterclear",
                              "filtersms2",
                              "filtersms3",
                              "filtersms4",
                              "filtersms5",
                              "filtersms6",
                              "filtersms7",
                              "filtersms8",
                              "filtersms9",
                              "firstpage",
                              "lastpage",
                              "guiprofile",
                              "red",
                              "green",
                              "yellow",
                              "blue",
                              "increasepar",
                              "decreasepar",
                              "volampup",
                              "volampdown",
                              "channelup",
                              "channeldown",
                              "previouschannelgroup",
                              "nextchannelgroup",
                              "leftclick",
                              "rightclick",
                              "middleclick",
                              "doubleclick",
                              "wheelup",
                              "wheeldown",
                              "mousedrag",
                              "mousemove",
                              "noop"
                            ], text)


